# IF YOU CHANGE THIS FILE, BE SURE TO RESTART ANY RUNNING JEKYLL SERVE INSTANCES

# --- PLUGINS ------------------------------------------------------------------

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# --- SITE DATA & SEO ----------------------------------------------------------

# Site's title
title: Jekyll Base

# Short description
tagline: Boilerplate starting point for new Jekyll sites.

# Longer description
description: Use this starter template to easily build out new Jekyll sites.

# Site's URL
url: https://www.domain.com

# SEO default share image (og:image, 1200x630)
logo: /images/seo/og.png

# --- NAVIGATION ---------------------------------------------------------------

nav:
  - title: Blog
    url: /blog/
  - title: Recipes
    url: /recipes/
  - title: Contact
    url: /contact/

# --- POST PERMALINKS ----------------------------------------------------------

permalink: /blog/:title/

# --- COLLECTIONS --------------------------------------------------------------

collections:
 recipes:
  output: true
  permalink: /recipes/:title/

# --- DEFAULTS -----------------------------------------------------------------

# Set defaults for post types

# Ideally the [image] variable below would pull in [site.logo] defined above
# to keep the code DRY, but variable substitution doesn't seem to work here.

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      image: /images/seo/og.png
  -
    scope:
      path: ""
      type: recipes
    values:
      layout: recipe
      image: /images/seo/og.png
  -
    scope:
      path: ""
      type: pages
    values:
      image: /images/seo/og.png
#  -
#    scope:
#      path: ""
#      type: recipes
#    values:
#      layout: recipe

# --- BUILD SETTINGS -----------------------------------------------------------

markdown: kramdown

# host: xxx.xxx.xxx.xxx
# destination: /var/www/domain.com

# Minifier settings
compress_html:

  # More aggressive
  # clippings: all

  # Less aggressive
  blanklines: true

  # Remove comments
  comments:  ["<!-- ", " -->"]

  # ignore:
  # envs: [development]

sass:
  sass_dir: style
  style: compressed

exclude:
  - README.md
  - docker-compose.yml
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
